export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
    /** Tenant-specific SCR-AUTH-01 entry (slug resolved server-side; no UUID in UI). */
    TENANT_LOGIN: (slug: string) => `/t/${encodeURIComponent(slug)}/login`,
    LOGOUT: '/logout',
    MFA_SETUP: '/mfa/setup',
    MFA_VERIFY: '/mfa/verify',
    PASSWORD_RESET: '/password-reset',
    PASSWORD_RESET_CONFIRM: '/password-reset/confirm',
    INVITATION_ACCEPT: '/invitations/accept',
    SESSION_EXPIRED: '/session-expired',
    UNAUTHORIZED: '/unauthorized',
    FORBIDDEN: '/forbidden',
  },
  PLATFORM: {
    ROOT: '/platform',
    DASHBOARD: '/platform/dashboard',
    TENANTS: '/platform/tenants',
    TENANTS_NEW: '/platform/tenants/new',
    TENANT_DETAIL: (tenantId: string) => `/platform/tenants/${tenantId}`,
    PLANS: '/platform/plans',
    USAGE: '/platform/usage',
    SUPPORT: '/platform/support',
    AUDIT: '/platform/audit',
    CONFIG: '/platform/config',
    CONFIG_GENERAL: '/platform/config/general',
    CONFIG_SECURITY: '/platform/config/security',
    CONFIG_RETENTION: '/platform/config/retention',
    CONFIG_REGIONS: '/platform/config/regions',
    CONFIG_NOTIFICATIONS: '/platform/config/notifications',
    CONFIG_INTEGRATIONS: '/platform/config/integrations',
    CONFIG_AUDIT_LOGGING: '/platform/config/audit-logging',
    INTEGRATION_HEALTH: '/platform/integration-health',
    PROFILE: '/platform/profile',
  },
  TENANT: {
    DASHBOARD: '/dashboard',
    HR: {
      ROOT: '/hr',
      SETTINGS: '/hr/settings',
    },
    ORGANISATION: {
      ROOT:                '/organisation',
      OVERVIEW:            '/organisation',
      GRADES:              '/organisation/grades',
      HISTORY:             '/organisation/history',
      LEGAL_ENTITIES:      '/organisation/legal-entities',
      LEGAL_ENTITY_NEW:    '/organisation/legal-entities/new',
      LEGAL_ENTITY_DETAIL: (id: string) => `/organisation/legal-entities/${id}`,
      BRANCHES:            '/organisation/branches',
      BRANCH_NEW:          '/organisation/branches/new',
      BRANCH_DETAIL:       (id: string) => `/organisation/branches/${id}`,
      DEPARTMENTS:         '/organisation/departments',
      DEPARTMENTS_TREE:    '/organisation/departments',
      DEPARTMENT_NEW:      '/organisation/departments/new',
      DEPARTMENT_DETAIL:   (id: string) => `/organisation/departments/${id}`,
      COST_CENTRES:        '/organisation/cost-centres',
      COST_CENTRE_NEW:     '/organisation/cost-centres/new',
      COST_CENTRE_DETAIL:  (id: string) => `/organisation/cost-centres/${id}`,
      POSITIONS:           '/organisation/positions',
      POSITION_NEW:        '/organisation/positions/new',
      POSITION_DETAIL:     (id: string) => `/organisation/positions/${id}`,
    },
    EMPLOYEES: {
      ROOT:          '/employees',
      NEW:           '/employees/new',
      IMPORT:        '/employees/import',
      DATA_QUALITY:  '/employees/data-quality',
      DETAIL:        (id: string) => `/employees/${id}`,
      EDIT:          (id: string) => `/employees/${id}/edit`,
      TRANSFER:      (id: string) => `/employees/${id}/transfer`,
      STATUS:        (id: string) => `/employees/${id}/status`,
      TIMELINE:      (id: string) => `/employees/${id}/timeline`,
    },
    DOCUMENTS: {
      ROOT:               '/documents',
      TEMPLATES:          '/documents/templates',
      TEMPLATE_NEW:       '/documents/templates/new',
      TEMPLATE_DETAIL:    (id: string) => `/documents/templates/${id}`,
      ONBOARDING:         '/documents/onboarding',
      ONBOARDING_NEW:     '/documents/onboarding/new',
      ONBOARDING_DETAIL:  (id: string) => `/documents/onboarding/${id}`,
    },
    ATTENDANCE: {
      ROOT:          '/attendance',
      RECORDS:       '/attendance/records',
      RECORD_DETAIL: (id: string) => `/attendance/records/${id}`,
      POLICIES:      '/attendance/policies',
      POLICY_NEW:    '/attendance/policies/new',
      POLICY_DETAIL: (id: string) => `/attendance/policies/${id}`,

      /** Attendance Capture (Batch 3) */
      CAPTURE: '/attendance/capture',
      DEVICES: '/attendance/devices',
      DEVICE_NEW: '/attendance/devices/new',
      DEVICE_DETAIL: (deviceId: string) => `/attendance/devices/${deviceId}`,
      DEVICE_PROVISION: (deviceId: string) =>
        `/attendance/devices/${deviceId}/provision`,
      GEOFENCES: '/attendance/geofences',
      GEOFENCE_NEW: '/attendance/geofences/new',
      GEOFENCE_DETAIL: (geofenceId: string) =>
        `/attendance/geofences/${geofenceId}`,
      GEOFENCE_EDIT: (geofenceId: string) =>
        `/attendance/geofences/${geofenceId}/edit`,
      OFFLINE_SESSIONS: '/attendance/offline-sessions',
      OFFLINE_SESSION_DETAIL: (sessionId: string) =>
        `/attendance/offline-sessions/${sessionId}`,
      EXCEPTIONS: '/attendance/exceptions',
      PERIOD_LOCK: '/attendance/period-lock',
    },
    LEAVE: {
      ROOT: '/leave',
      REQUESTS: '/leave/requests',
      REQUEST_DETAIL: (id: string) => `/leave/requests/${id}`,
      TYPES: '/leave/types',
      POLICIES: '/leave/policies',
      ADJUST: '/leave/adjustments',
      NEW: '/leave/requests/new',
    },
    APPROVALS: {
      ROOT: '/approvals',
      DETAIL: (id: string) => `/approvals/${id}`,
      WORKFLOWS: '/approvals/workflows',
      WORKFLOW_NEW: '/approvals/workflows/new',
      DELEGATION: '/approvals/delegation',
      HISTORY: '/approvals/history',
    },
    SHIFTS: {
      ROOT: '/shifts',
      NEW: '/shifts/new',
      DETAIL: (shiftId: string) => `/shifts/${shiftId}`,
      EDIT: (shiftId: string) => `/shifts/${shiftId}/edit`,
      ASSIGN: '/shifts/assign',
      ASSIGNMENTS: '/shifts/assignments',
      ROSTER: '/shifts/roster',
    },
    PAYROLL: {
      ROOT: '/payroll',
      PERIODS: '/payroll/periods',
      PAYSLIPS: '/payroll/payslips',
      PUBLISH: '/payroll/payslips/publish',
    },
    REPORTS: {
      ROOT: '/reports',
      VIEWER: (code: string) => `/reports/${code}`,
    },
    INTEGRATIONS: {
      ROOT: '/integrations',
      DETAIL: (id: string) => `/integrations/${id}`,
      SETUP: (id: string) => `/integrations/${id}/setup`,
      HEALTH: '/integrations/health',
      CREDENTIALS: '/integrations/credentials',
      BIOMETRIC: '/integrations/biometric',
      BIOMETRIC_MAPPING: '/integrations/biometric/mapping',
    },
    SUBSCRIPTION: '/subscription',
    SETTINGS: '/settings',
    SETTINGS_COMPANY: '/settings/company',
    SETTINGS_BRANDING: '/settings/branding',
    SETTINGS_REGIONAL: '/settings/regional',
    SETTINGS_USERS: '/settings/users',
    SETTINGS_ROLES: '/settings/roles',
    SETTINGS_MODULES: '/settings/modules',
    SETTINGS_SECURITY: '/settings/security',
    SETTINGS_SESSIONS: '/settings/sessions',
    SETTINGS_CUSTOM_FIELDS: '/settings/custom-fields',
    SETTINGS_HOLIDAY_CALENDAR: '/settings/holiday-calendar',
    SETTINGS_PAYROLL_CALENDAR: '/settings/payroll-calendar',
    SETTINGS_SUBSCRIPTION: '/settings/subscription',
    SETTINGS_SUBSCRIPTION_COMPARE: '/settings/subscription/compare',
    AUDIT: '/audit',
    AUDIT_DETAIL: (id: string) => `/audit/${id}`,
  },
  EMPLOYEE: {
    DASHBOARD: '/my',
    ATTENDANCE: '/my/attendance',
    ATTENDANCE_CHECK_IN: '/my/attendance/check-in',
    ATTENDANCE_CHECK_OUT: '/my/attendance/check-out',
    ATTENDANCE_DAY: (date: string) => `/my/attendance/${encodeURIComponent(date)}`,
    ATTENDANCE_CORRECTION: '/my/attendance/correction',
    REQUESTS: '/my/requests',
    REQUEST_DETAIL: (id: string) => `/my/requests/${id}`,
    REQUEST_NEW: '/my/requests/new',
    DOCUMENTS: '/my/documents',
    NOTIFICATIONS: '/my/notifications',
    POLICIES: '/my/policies',
    ROSTER: '/my/roster',
    LEAVE: '/my/leave',
    LEAVE_NEW: '/my/leave/new',
    LEAVE_DETAIL: (id: string) => `/my/leave/${id}`,
    PAYSLIPS: '/my/payslips',
    PAYSLIP_DETAIL: (id: string) => `/my/payslips/${id}`,
    PROFILE: '/my/profile',
    MORE: '/my/more',
  },
} as const;
